### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by rsperlazza** [rsperlazza/DeleteThis#41]
- [ ] Bugs.1.1 DBUtil convertAttributeToText function doesn't check if attrValue is null: This bombs a lot of different reports. Easiest way to get this is setting an entity's duration to null.
- [ ] Bugs.1.10 Can't resize sidebar on mobile: the dragging stuff gets really messed up. I'm assuming we aren't doing it right
- [ ] Bugs.1.11 "Create new" in schema view signed out errors: from schema view click labels (or classes, relations, any of them work) click create new whatever in a seperate tab sign out in the main tab click back the signout alert comes up and you get a couple of errors to the console. We should probably catch these since we know the problem is the user not being signed in.
- [ ] Bugs.1.12 Project Description Edit when description has a picture while signed out: Make a project and upload a picture to its project description in another tab log out click to edit the description The initial click throws 401 errors, and then everytime you type in the field it throws another 401 error. Probably need to check for sign in here somewhere. This happens everywhere you can edit the project description.
- [ ] Bugs.1.13 Entity View Permissions Issue: same as #2970 except in entity view. Need to check if the user can edit the entities before trying to save them.
- [ ] Bugs.1.14 Open Dropdown menu css gets weird when you have a top project banner: If you have a top project banner displayed, the open dropdown css gets out of whack when there are a lot of options (i.e. pick an Action or Asset) and when your window size is between ~700-743px
- [ ] Bugs.1.15 Trying to branch a project while signed out shows the re-sign in modal but if you don't have a license the sign in modal gets stuck with no error message
- [ ] Bugs.1.16 VSelect focus border shouldn't appear when 1st clicking into the select to match the behavior of the default select element
- [ ] Bugs.1.17 Make 1 Util function that does both uploadExistingImage and uploadNewImage and replace all other uses with that function
- [ ] Bugs.1.18 Updating users/teams in the share project modal should update the `window.App.db.users`/`window.App.db.teams` arrays: You should be able to share your project with someone and then navigate to a Task and set them as the Assignee without having to refresh the page.
- [ ] Bugs.1.19 Certain views have other fetches that when you re-sign in with the modal they don't get called again and either spin forever or show an empty widget message: Database View: Schema when switching to the overview tab:
- [ ] Bugs.1.2 Redactor text color dropdown tabs should be white when active and gray when inactive: Right now the gray tab (Text in this case) is the active one which is backwards and confusing.
- [ ] Bugs.1.20 When importing points for XY Plot you shouldn't be able to remove the last dataset: Also if you remove the last dataset from the modal after importing, the entity mode checkbox correctly enables itself again but the label doesn't have `cursor: pointer`
- [ ] Bugs.1.21 Deleting a project/organization should remove the project(s) as options for the recent projects fetch in the backend: Used in HeaderNavbar with `DatabaseServiceFactory.getRecentProjects(10)`
- [ ] Bugs.1.22 Running auto-number without a prefix always puts 1 in as the prefix: It should just allow you to do it without a prefix
- [ ] Bugs.1.23 All modals need to have more dynamic max-heights for scrolling as the footer buttons disappear on smaller screens: Related to #3077. The styles added in that fix are roughly how we'd want to do this. This will need to be split up more by view. It's pretty much every modal but here's a few examples of modals with this issue: Database Settings Table Notation Add Widget (particularly with inno cards) Chart View Datasets Chart Settings
- [ ] Bugs.1.24 All Existing Widget if search succeeds but doesn't return any entities the count in the footer doesn't update: Start with a couple of diagrams in the widget and then change the search so that none show up. Notice the count in the footer didn't update.
- [ ] Bugs.1.25 In database view if you click the update button while signed out it shows the sign in modal which after signing back in shows a double scrollbar and the whole page has ~60px of blank space below it
- [ ] Bugs.1.26 Add links to all text containing #ISSUE_NUMBER: Issue and PR titles should not have this probably just add markdown to comments and descriptions in modals at this point related to #3085
- [ ] Bugs.1.27 Move '.toolbar-button' into /assets/css/styles.css: We use this class a ton so making it global makes sense. These files may need to be double checked, other toolbars should be good: Requirements.vue Timeline.vue
- [ ] Bugs.1.28 Acronym extractor with multiple definitions for the same entity needs to keep track of each of the indices: If you add an acronym and give it 2+ different definitions and choose to replace the acronyms with a link to the acronym's definition entity, the acronym extractor will replace ALL the matching acronyms with a link to the last definition. For example, in the test case below, both uses of "NBA" will be replaced with a link to the National Business Agents acronym definition entity. We should fix this and also show the user a list of all the specific definitions to choose for each entity and replace them accordingly. My new acronym NBA (National Basketball Association). Another acronym is NBA (National Business Agents).
- [ ] Bugs.1.29 When activating an account if you happen to sign in with a different account that goes to an organization other than demo it randomly redirects you to demo dashboard once the countdown timer finishes: Should probably just get rid of the countdown.
- [ ] Bugs.1.3 Future fixes for tour: Innoslate 101 tour: allow starting tour from a view other than project dashboard allow tour to go to manage projects view and org dashboard without cancelling the tour prompt users who leave the tour and come back to either continue with the tour or exit it update tour .inno files after chart thumbnail import/export fixes (this is part of the import/export fix already) TourDetailsModal fixes
- [ ] Bugs.1.30 Add/Remove User License: Example: You have an org with 2 named users. Then in the Edit License Panel you drop the count from 2 -> 1 and save it. Who should be the user that loses the license? We need to tell the admin who just lost there license. If you drop the count to 0 we should tell them that everyone was just removed.
- [ ] Bugs.1.31 Diagrams should all save before capturing the image so if the save fails the image doesn't get out of sync
- [ ] Bugs.1.32 Change Console Panel in MonteCarlo sim to only display each run (i.e. Run #1, Run #2, etc) and then show the printed statements when the user clicks to expand the specific run: This should help prevent blowing up the DOM with a bunch of prints in a large MonteCarlo sim.
- [ ] Bugs.1.33 Middle Click doesn't work on the projects in the My Projects widget in org dashboard: Need to convert the s to s
- [ ] Bugs.1.34 Add a 'Save Layout' or 'Save Dashboard' button to the dashboard framework: Right now changes only get saved if you route away within Innoslate but I imagine people will be confused when they make a bunch of dashboard changes and then sign out which would quietly discard those changes.
- [ ] Bugs.1.35 "Number is too long" error shown when creating new document: click "Create Document" button give a name and click next (number is optional) pick "custom template" click "prev" button shows error even though no number is there
- [ ] Bugs.1.36 Radar Diagram sort 'Number and Name' option should be listed consistently: The 'Manually' option also just says 'Manual' in the toolbar when you choose that one. Use consistent naming conventions.
- [ ] Bugs.1.37 Discrete sim in step mode if you double click the play button fast enough it gets into a weird state of the sidebar thinking it's running but the sim itself is still paused
- [ ] Bugs.1.38 Resource script with invalid global id (i.e. after import, resource with global id doesn't exist) the Loop Resource tab of the script modal gets stuck and doesn't let you change the global id: You can technically change it directly through the 'Script' tab but it should allow you to do it here as well.
- [ ] Bugs.1.39 Manage views' footer needs to update with the correct counts when searching for a diagram/chart/document/test center/dodaf: If you have 2+ pages worth of diagrams/charts/etc: Search for one of them with the input Once it loads, click the next button Click the previous button Notice that the card you searched for has duplicated. You can continue repeating 2 & 3 and it'll keep duplicating the cards. This should just show the correct count based on your search criteria and this wouldn't be an issue and would make more sense from a UI perspective.
- [ ] Bugs.1.4 PM Dashboard Widgets: If you have a widget with a dropdown menu too low on the screen it makes the dropdown menu expand upwards, hiding all the options behind the card header
- [ ] Bugs.1.40 Sopatra open dropdowns need to handle empty lists and lists with a few items better: If the open dropdown has nothing or like 1-2 things it looks bad
- [ ] Bugs.1.41 Relationship attribute modal in spider diagram needs a 'Cancel' button for consistency with other modals
- [ ] Bugs.1.42 Github Pull Requests dashboard needs to re-calculate the widget/scroll height when the search changes
- [ ] Bugs.1.43 Schema Hidden Classes Showing Up: Hidden classes in the schema are still showing up in the Spider diagram menu even when they are not shown in the Database
- [ ] Bugs.1.5 Sidebar should hide itself on small screens: Sidebar should automatically hide itself at smaller screen sizes
- [ ] Bugs.1.6 Permissions checker doesn't seem to be working: Steps to recreate: make a new user go on an admin account and add the new user to an org as a "Named User" with the org role of "Reviewer" Share a project with the new user. Give them "Reviewer" permissions on the project Log on the new user and navigate to the project. This error pops up This only works if you initially add the user as a Reviewer to the project. If you start them as a Member and then make them a Reviewer from the widget this error doesn't happen.
- [ ] Bugs.1.7 Users with no license for an org can create projects on that org: They can create the project, but can't navigate to it
- [ ] Bugs.1.8 Weird behavior when inside a project as its license expires: go to a project duplicate tab in new tab, go to admin dash and set the license expire date to some date in the past close new tab in old tab try to navigate around, log out, log out in a new tab, etc Doing those things causes weird stuff to happen. I'll screen cap what happens once we merge this stuff back to github. For instance, sometimes when you log back in your currentUser is set to null and none of your user info is displayed
- [ ] Bugs.1.9 Direct Message Window: Stale name: If a user changes their name while you have a dm open with them, the name at the top of the tab doesn't update
